insert produtos(descricao,nome,preco) values('descrição1','produto1',10);
insert into produtos(descricao,nome,preco) values('descrição2','produto2',10);
insert into produtos(descricao,nome,preco) values('descrição3','produto3',10);
insert into produtos(descricao,nome,preco) values('descrição4','produto4',10);
insert into produtos(descricao,nome,preco) values('descrição5','produto5',10);
insert into produtos(descricao,nome,preco) values('descrição6','produto6',10);
insert into produtos(descricao,nome,preco) values('descrição7','produto7',10);
insert into produtos(descricao,nome,preco) values('descrição8','produto8',10);
insert into produtos(descricao,nome,preco) values('descrição9','produto9',10);
insert into produtos(descricao,nome,preco) values('descrição10','produto10', 10);
insert into produtos(descricao,nome,preco) values('descrição11','produto12', 10);
insert into produtos(descricao,nome,preco) values('descrição12','produto13', 10);
insert into produtos(descricao,nome,preco) values('descrição13','produto14', 10);
insert into produtos(descricao,nome,preco) values('descrição14','produto15', 10);
insert into produtos(descricao,nome,preco) values('descrição15','produto16', 10);
insert into produtos(descricao,nome,preco) values('descrição16','produto17', 10);
insert into produtos(descricao,nome,preco) values('descrição17','produto18', 10);
insert into produtos(descricao,nome,preco) values('descrição18','produto19', 10);
insert into produtos(descricao,nome,preco) values('descrição19','produto20', 10);
insert into produtos(descricao,nome,preco) values('descrição20','produto21', 10);
insert into produtos(descricao,nome,preco) values('descrição21','produto22', 10);
insert into produtos(descricao,nome,preco) values('descrição22','produto23', 10);
insert into produtos(descricao,nome,preco) values('descrição23','produto24', 10);
insert into produtos(descricao,nome,preco) values('descrição24','produto25', 10);
insert into produtos(descricao,nome,preco) values('descrição25','produto26', 10);